### ISSUE TITLE
Game Crash on Heart clear

### ISSUE THREAD

**Issue by mezzoEmrys** [mezzoEmrys/TheJester#1]
Game crashes during NeowUnlockScreen.open with out of bounds exception, 0 out of len 0.

01:35:12.096 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_181]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_181]
    at com.megacrit.cardcrawl.neow.NeowUnlockScreen.open(NeowUnlockScreen.java:56) ~[desktop-1.0.jar:?]
    at com.megacrit.cardcrawl.screens.VictoryScreen.update(VictoryScreen.java:849) ~[desktop-1.0.jar:?]
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2583) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by mezzoEmrys** [comment]
Seems to be related to not having any unlocks. Is this a BaseMod bug?

**Comment by mezzoEmrys** [comment]
Solving seems to involve making Unlock bundles, but I don't have 15 things for this class to unlock. I'm not sure if using AbstractUnlock.UnlockType.MISC with three empty IDs is enough to solve things, given that there is no reference to MISC anywhere outside of NeowUnlockScreen.
